//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDDuack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoteles
    {
        public int Id { get; set; }
        public string nombre { get; set; }
        public float latitud { get; set; }
        public float longitud { get; set; }
        public string direccion { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string pais { get; set; }
        public Nullable<float> precio { get; set; }
        public string idioma { get; set; }
        public string foto { get; set; }
        public string telefono { get; set; }
        public string url { get; set; }
    }
}
